language: shell
os: linux
dist: focal
git:
  depth: 3

addons:
  apt:
    update: true
    packages:
      - shellcheck

install: skip

script:
  - shellcheck -x wofi-pass
  - ./bash_unit/bash_unit -f tap ./tests/test_*
